from turtle import *
canvas = Screen()
canvas.setup(600,400)
kyle = Turtle()
kyle.shape("turtle")
kyle.color("blue")
kyle.left(90)
kyle.forward(60)
kyle.left(90)
kyle.forward(30)
kyle.right(180)
kyle.forward(60)
from turtle import *
canvas = Screen()
canvas.setup(600,400)
kyle = Turtle()
kyle.shape("turtle")
kyle.color("yellow")
kyle.forward(30)
kyle.left(50)
kyle.forward(60)
kyle.right(90)
kyle.forward(30)
kyle.right(50)
kyle.right(90)
kyle.forward(30)
kyle.right(180)
kyle.forward(30)
kyle.right(60)
kyle.forward(30)
from turtle import *
canvas = Screen()
canvas.setup(600,400)
kyle = Turtle()
kyle.shape("turtle")
kyle.color("red")
kyle.forward(120)
kyle.left(90)
kyle.forward(20)
kyle.left(30)
kyle.forward(20)
kyle.right(180)
kyle.forward(20)
kyle.left(100)
kyle.forward(30)
from turtle import *
canvas = Screen()
canvas.setup(600,400)
kyle = Turtle()
kyle.shape("turtle")
kyle.color("green")
kyle.forward(150)
kyle.left(90)
kyle.forward(50)
kyle.right(180)
kyle.forward(50)
kyle.left(90)
kyle.forward(20)
from turtle import *
canvas = Screen()
canvas.setup(600,400)
kyle = Turtle()
kyle.shape("turtle")
kyle.color("orange")
kyle.forward(180)
kyle.left(90)
kyle.forward(50)
