from turtle import *
canvas = Screen()
canvas.setup(1600,400)
ryley = Turtle()
ryley.shape("turtle")
ryley.color("#00ffb7")
#Makes Letter R
ryley.left(90)
ryley.forward(200)
ryley.right(90)
ryley.forward(100)
ryley.right(90)
ryley.forward(50)
ryley.right(90)
ryley.forward(100)
ryley.left(115)
ryley.forward(165)
#space between the R and Y
ryley.up()
ryley.left(65)
ryley.forward(100)
ryley.down()
#Makes Letter Y
ryley.left(90)
ryley.forward(150)
ryley.left(45)
ryley.forward(50)
ryley.left(180)
ryley.forward(50)
ryley.left(85)
ryley.forward(50)
#space between the Y and L
ryley.up()
ryley.right(40)
ryley.forward(100)
ryley.down()
#Makes the letter L
ryley.right(90)
ryley.forward(180)
ryley.left(90)
ryley.forward(100)
#space between the L and E
ryley.up()
ryley.forward(150)
ryley.down()
#make the leter E
ryley.forward(50)
ryley.left(180)
ryley.forward(50)
ryley.right(90)
ryley.forward(150)
ryley.right(90)
ryley.forward(50)
ryley.left(180)
ryley.forward(50)
ryley.left(90)
ryley.forward(75)
ryley.left(90)
ryley.forward(50)
ryley.left(180)
ryley.forward(50)
ryley.left(90)
ryley.forward(75)
ryley.left(90)
ryley.forward(50)
#space between the E and Y
ryley.up()
ryley.forward(150)
ryley.down()
#Make the letter Y
ryley.left(90)
ryley.forward(150)
ryley.left(45)
ryley.forward(50)
ryley.left(180)
ryley.forward(50)
ryley.left(85)
ryley.forward(50)



